# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
  containers:
  - container: linux # reusable alias
    image: dajiejie123/dajiejie

jobs:
- job: a
  container: linux # reference

- job: b
  container: linux # reference
