resources:
  containers:
  - container: my_container
    image: dajiejie123/dajiejie

pool:
  vmImage: 'ubuntu-16.04'

container: my_container

services:
  my_container: my_container

steps:
- script: |
    cd /home && ./sgx-init
    
    
